### ISSUE TITLE
Rate Limiting urls

### ISSUE THREAD

**Issue by starlightromero** [Placita/placita#20]
> This endpoint handler performs a file system operation and does not use a rate-limiting mechanism. It may enable the attackers to perform Denial-of-service attacks. Consider using a rate-limiting middleware such as express-limit.

I found this middleware to be better maintained than `express-limit`

[https://github.com/nfriedly/express-rate-limit](url)

> Basic rate-limiting middleware for Express. Use to limit repeated requests to public APIs and/or endpoints such as password reset.

**Comment by sidneyarcidiacono** [comment]
This issue is addressed with PR #28.
